name: smilecheck
description: AI-based dental caries detection system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.0.7
  camera: ^0.10.5
  share_plus: ^9.0.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true